### ISSUE TITLE
Support for Styled Components in React - It seems like an absolute necessity

### ISSUE THREAD

**Issue by yedhink** [tailwindcss/intellisense#106]
Thanks for the plugin. Most often i use tailwind macro in a styled component while doing react. But it seems that the auto-completions are not triggered inside a styled component for react. Example:-
```js
const MainStyle = styled.main.attrs({
    // these wont get triggered for auto-completion unless i change ':' to '=' after 'className'
    className:"flex flex-col bg-gray-900 m-0 h-screen w-auto",
})`i cant get auto completion for tailwind within template literals too`
```
I'm not sure how this plugin triggers the auto-completion. But if the trigger area is fixed using a regex, would adding a regex similar tot this, to the possible patterns work(im not that good with regex, but still)?
```
styled.*[\`|\(](.*)\`$
```
Patterns of code that should be matched:-
```js
styled.xxx``

styled.xxx.attrs({})``
```

**Comment by JDDoesDev** [comment]
I think this would need to be configurable for people to use either styled, Twin, tailwind.macro, etc.  Maybe something available in settings.json like
```json
{
  autocompleteTailwindIn: [
    'tw',
    'twin',
    'styled'
  ]
}
```
where the array values get injected into the pattern matching section.

**Comment by yedhink** [comment]
@JDDoesDev I'm not quite understanding the usecase of having such a configuration option. Like the auto-completion is triggered using regex is what i believe. So when the cursor enters either the tailwind macro par or inside the styled section, then also automatically the suggestion should popup right?

**Comment by zamson** [comment]
Support for the twin.macro and Emotion would be really handy

**Comment by timfee** [comment]
Have you tried editing your `settings.json` as follows?

```json
  "tailwindCSS.includeLanguages": {
    "html": "javascript"
  }
```

Everything seems to work:

<img width="770" alt="completions" src="https://user-images.githubusercontent.com/3246342/86312536-cbd02500-bbd7-11ea-81ad-f32c1841b47a.png">

**Comment by will-t-harris** [comment]
@timfee: I tried changing my `settings.json` in the way you recommended, but I'm still not getting autocomplete to work in my project. 

For reference, I'm trying to get the autocomplete working with `twin.macro`

**Comment by timfee** [comment]
> @timfee: I tried changing my `settings.json` in the way you recommended, but I'm still not getting autocomplete to work in my project.
> 
> For reference, I'm trying to get the autocomplete working with `twin.macro`

Ah, in that case, you need to specify `macro` as the language. See [the related setting documentation](https://github.com/tailwindcss/intellisense#tailwindcssincludelanguages) -- any luck?

**Comment by will-t-harris** [comment]
I'm not sure that I follow your suggestion.

I've tried both

```
 "tailwindCSS.includeLanguages": {
    "macro": "javascript"
  }
```
and
```
 "tailwindCSS.includeLanguages": {
    "html": "macro"
  }
```
Neither got autocomplete to work.

**Comment by timfee** [comment]
I'm not sure what extension `macro` is, or if using HTML language settings would make it hard to use, but if you Ctrl+P and choose **Change language mode** and set to HTML, does that work for you?

<img width="590" alt="Screen Shot 2020-07-02 at 8 27 51 PM" src="https://user-images.githubusercontent.com/3246342/86428913-c7bd0980-bca2-11ea-8d2a-ec7618683eff.png">

**Comment by will-t-harris** [comment]
Thanks for getting back to me, I'm using React so setting the language mode to HTML is not really sustainable.

Regardless, it allow for class autocompletion. It seems the solution I'm looking for is on the team's radar: #129

**Comment by bradlc** [comment]
Yeah, I think this falls under #129 as well
