### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by bradlc** [tailwindcss/intellisense#128]
I think this might be a related issue but since 3.0 this stopped working on some of my projects. I narrowed down to the fact that I use pnpm for all my projects since when I install  node_modules with yarn or npm it does work as expected.

I already tested with a empty  vscode profile `code --user-data-dir ~/.vscode-test --extensions-dir ~/.vscode-test-extentions` so I was sure that no other plugin was interfering with the test.

For now I'm downgrading to 2.0

_Originally posted by @cesasol in https://github.com/bradlc/vscode-tailwindcss/issues/127#issuecomment-644270659_

**Comment by cesasol** [comment]
There is a way in which I can help you test?. I did read the code but honestly I didn't understand it.

**Comment by davelsan** [comment]
I also use [pnpm](https://pnpm.js.org/) for all my projects and I can reproduce this bug. Non-monorepo projects also have this problem.

Downgrading to 2.0 fixes the issue.

**Comment by bradlc** [comment]
Module resolution has been rejigged in `v0.4.0` to support pnpm. Let me know if you're still having problems

**Comment by kn0wn** [comment]
Hi @bradlc, There still seems to be issues with pnpm where no suggestions are being made - I just disabled all extensions apart from tailwind intellisense and the issue is still there, is there any debug information I can send you?
