### ISSUE TITLE
Feature Request: Intellisense in TailwindCSS React Native tailwind() function 🙏 

### ISSUE THREAD

**Issue by tommulkins** [tailwindcss/intellisense#132]
How great would it be if we could also have intellisense inside the `tailwind()` function provided by https://github.com/vadimdemedes/tailwind-rn package?

For example, 
```
<Text style={tailwind('text-center text-white text-2xl')}>
  SIGN UP
</Text>
```

Any plans to include this too by any chance? 😄

**Comment by bradlc** [comment]
Hey @tommulkins. I think #129 would cover this

**Comment by jumoel** [comment]
Until #129 is done, getting intellisense working in React Native with `tailwind-rn` is possible by tricking the intellisense plugin :) You can write a HOC to allow `className` props to work with Tailwind in RN:

```js
function withTailwind(Component) {
  function ComponentWithTailwind({ className, style, ...rest }) {
    const classes = className
      ? Array.isArray(className)
        ? className.flat().filter(Boolean).join(" ")
        : className
      : "";

    return <Component style={[tailwind(classes), style && style]} {...rest} />;
  }

  ComponentWithTailwind.displayName = `withTailWind(${getDisplayName(
    Component
  )})`;

  return ComponentWithTailwind;
}
```

<img width="549" alt="tailwind-intellisense" src="https://user-images.githubusercontent.com/18848/91977708-54c42380-ed23-11ea-849d-71ba839e3419.png">

(More details here: https://www.jumoel.com/posts/tailwind-react-native-classnames)

**Comment by realmichaelye** [comment]
+1 for this, please add tailwind-rn support

**Comment by harshjadon9** [comment]
+1
 please add tailwind-rn support

**Comment by enchorb** [comment]
+1
