### ISSUE TITLE
cssConflict too conflictual

### ISSUE THREAD

**Issue by matthieudou** [tailwindcss/intellisense#135]
Hi,

First of all, thanks for this extension, the new additions are 🔥 , love it.
I'm seeing a little "bug" (not sure it's a bug) where it seems to conflict with two variants.
One is the `focus` variant from tailwindcss and the other one is `kb-focus`, a custom variant that exists only when the keyboard is used.

Any idea of what I could do to fix this ?

Thanks by advance

![image](https://user-images.githubusercontent.com/18487606/85570283-82aa2f00-b633-11ea-868a-ce2a926bfb5a.png)

**Comment by bradlc** [comment]
Hey @matthieudou. Which version of the extension do you have installed? I just pushed out `v0.4.1` today which should fix this. Let me know if not!

**Comment by matthieudou** [comment]
Just installed the latest version ! Works like a charm now. Thanks !
