### ISSUE TITLE
tailwindCSS.includeLanguages setting not work

### ISSUE THREAD

**Issue by NoviceDuke** [tailwindcss/intellisense#143]
I use tailwind css with in laravel

need to set vue and blade file 

this is my settings 
`"tailwindCSS.includeLanguages": {
    "blade": "html",
    "php": "html",
    "vue" : "html"
}`

I am sure about the extension is work via make a simple .html file in this laravel project and type some tailwind style

laravel version :6

tailwind css inellisense version : 0.4.1

Thanks for helping me

====

Update the issue more detail

I found the problem is the laravel blade file with use some code like
`@extension @section`
if we code in @ tag  and the extension will not work

but outside the tag will work with languages setting

**Comment by alzaabi98** [comment]
I have same issue autocomplete does not work for in html or in laravel blade

**Comment by iiiyu** [comment]
I have the same issue too.


Laravel version: 7.x

tailwind css inellisense version : 0.4.1

**Comment by yabdab** [comment]
Same here, not sure why this issue is closed?
