### ISSUE TITLE
Any solution to warnings issued because of templating conditionals

### ISSUE THREAD

**Issue by snapey** [tailwindcss/intellisense#144]
Using blade template tags within the class statement;
```
                @if($note->pinned)
                    border-red-500
                @else
                    border-teal-500
                @endif
```
I get warnings on the duplication of the tailwind class (cssConflict).

Any suggestions?  I don't want to duplicate the whole class statement (putting the conditionals around the class, not inside it).

_using vscode and v0.4.1_

**Comment by bradlc** [comment]
If you write it like this you won't get conflict warnings:

```html
<div class="{{ $note->pinned ? 'border-red-500' : 'border-teal-500' }}"></div>
```

**Comment by snapey** [comment]
Nice. I use that pattern occasionally. I'll have to remember to use it more.
